name: Deploy to Cloud Run


on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }} # is this really secret?

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: {{ env.SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - run: gcloud projects list

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run jobs deploy my-service \
      #       --image gcr.io/${{ env.PROJECT_ID }}/my-image:latest \
      #       --region ${{ env.PROJECT_ID }} \
      #       --platform managed
